name: Build docker image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Create license
        run: |
            echo "${{ secrets.STATA_LIC_BASE64 }}" | base64 -d > stata.lic 
            ls -l stata.lic
      - name: Sanitize repo slug
        uses: actions/github-script@v4
        id: repo_slug
        with:
          result-encoding: string
          script: return '${{ github.repository }}'.toLowerCase()

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run code
        run: |
            chmod a+rx ./run.sh
            ./run.sh stata.lic
      - name: Commit results
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          user_name: 'Github Action Bot'
          user_email: lars.vilhuber@cornell.edu
          publish_branch: gh-pages 
          keep_files: true
          commit_message: ${{ github.event.head_commit.message }}