name: Build docker image

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Dockerfile'
      - 'build.sh'
      - 'build.yml'
      - 'setup.do'
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      # This needs to be adapted to your own PROJECT!!
      # It may not correspond to your Docker login
      # DOCKER_PROJECT: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKER_PROJECT: aeadataeditor
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Create license
        run: |
            echo "${{ secrets.STATA_LIC_BASE64 }}" | base64 -d > stata.lic 
            ls -l stata.lic
            rm config.txt
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Sanitize repo slug
        uses: actions/github-script@v4
        id: repo_slug
        with:
          result-encoding: string
          script: return '${{ github.event.repository.name }}'.toLowerCase()

      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_PROJECT }}/${{ steps.repo_slug.outputs.result }}:latest
          secret-files: |
             "statalic=./stata.lic"
